### PR TITLE
fix: remove tooltip on exit chart area

### LINKED ISSUE #62: Remove hover tooltip when chart is no longer being hovered.
**Given:**
- A chart with tooltip displayed on hover
- On initial load - no tooltip is displayed ✅
- A user starts hovering the chart - tooltip is displayed ✅ 

**When:**
- A user moves the mouse outside of the chart area

**Then:**
- Expected:
  - The tooltip is removed
- Reality:
  - The tooltip is forever displayed ❌  

https://user-images.githubusercontent.com/1267623/158693734-7a5ee798-9c14-4a33-baa9-a3040fb8f539.mov

### PR DESCRIPTION
**Pull request by canastro**
Just opening this as a show-case of my failed attempt to fix #62. 

It fixes the case where the user moves the mouse outside the area of the chart, but if the user alt-tabs to another window and then back to the flutter window the tooltip is left open forever.

Maybe this is ok, and two other things could be added:
1. a TTL for tooltips
2. a way of allowing the consumer of the chart to indicate if hover is enabled, it would to the consumer to control if the window is focused or not.
 
Maybe n.2 is possible, I'm still pretty new with this lib.

Let me know your thoughts about this.

### CODE REVIEW

**Comment by entronad** [comment]
Thanks a lot!

In the beginning Flutter is only for mobile, so the gesture system mainly focuses on touching cases (so called "touch first"). 

When using fingers, there is no problem: Wen your finger left the screen, you still want the tooltip shown; and you rarely "drag out" your finger from the chart border. If you want the tooltip hidden, just need to double tap.

But when web and desktop devices added to Flutter, the mouse interaction is getting important. It is quite different: your mouse is forever on the screen (in the status of "hover"); and people don't like to "click" or "drag" to trigger the tooltip. So "hover out" the chart becomes a frequent case.

The basic logic of selection(which controls the tooltip) of Graphic is that it triggers by `on` signals and hides by `off` signals. which means "the `on` signals disappear" or "there is no signal" is not the condition to hide the tooltip.

The problem is there is no such event like "onmouseleave" in the Flutter gesture detector.

File: lib/src/coord/coord.dart [hunk 1]
```diff
@@ -9,8 +9,8 @@ import 'package:graphic/src/dataflow/tuple.dart';
 import 'package:graphic/src/graffiti/scene.dart';
 import 'package:graphic/src/util/assert.dart';
 
-import 'rect.dart';
 import 'polar.dart';
+import 'rect.dart';
```
Comment (canastro) [inline lib/src/coord/coord.dart:13]: these were due to my auto saving formatter. I'll rollback if we move forward with this PR.

File: lib/src/chart/chart.dart [hunk 2]
```diff
@@ -213,6 +214,19 @@ class _ChartState<D> extends State<Chart<D>> {
   /// Details of previous scale update.
   ScaleUpdateDetails? gestureScaleDetail;
 
+  /// Keep track if there is a mouse connected.
+  late bool _mouseIsConnected;
+
+  @override
+  void initState() {
```
Comment (canastro) [inline lib/src/chart/chart.dart:221]: I followed the approach of Flutter's tooltips. I check if theres a mouse, and if yes, I add a MouseRegion.

**Comment by canastro** [comment]
Thank you for your quick answer @entronad!
So I tried something a bit different and more inline on how Flutter deals with tooltips.

Basically a MouseRegion is only added if a mouse is connected. And then a mouseExit "gesture" can be used to clear the tooltip.

https://user-images.githubusercontent.com/1267623/158814309-02c450c7-cc28-4c2e-b16f-6f005692d436.mov

Let me know what you think of this approach.

**Comment by entronad** [comment]
Your approach seems fine as I reviewed. It's quite a good work!

I will be glad to merge this PR.

**Comment by canastro** [comment]
Thank you! Reverted the files that only changes were imports reordering and made the PR ready for review.

Hopefully we (me and @bernarndobelchior) will be able to use this in our project and we'll be contributing with more inputs to this already awesome charting library!

**Comment by entronad** [comment]
Thanks for your praise! If convenient, please introduce this lib to the dev community in your country.

**Comment by canastro** [comment]
Once we get more familiar with it we’ll definitely write something about it !  In my Opinion, this lib is light years ahead of the “competition“, and it’s amazing how you did all this by yourself

**Comment by entronad** [comment]
Published in v0.9.2

**Comment by entronad** [comment]
Is the `_mouseIsConnected` checking really necessary?

The key part of this PR is that the `MouseRegion` provides the `onEnter` and `onExit`, the `_mouseIsConnected` checking is to make sure they only emitted for mouse.

But as I tried, if not checking the mouse and always adding the `MouseRegion`, they are also only emitted for mouse. Thus the checking seems unnecessary, especially it takes a lot of code involving `RendererBinding`.

**Comment by canastro** [comment]
It might be a premature optimization, but it was something I copied from Flutter's tooltip implementation here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tooltip.dart#L354

**Comment by entronad** [comment]
@canastro 
Got it. That's good.
